[project]
name = "edon"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "loguru>=0.7.3",
    "pyside6>=6.9.0",
]

[tool.ruff]
line-length = 119

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[dependency-groups]
dev = [
    "basedpyright>=1.29.1",
]

[tool.hatch.build.targets.wheel]
packages = ["src/edon", "src/edon_ui"]
