[project]
name = "edon"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "loguru>=0.7.3",
    "pyside6>=6.9.0",
    "qtawesome>=1.4.0",
    "thefuzz[speedup]>=0.22.1",
]

[tool.ruff]
line-length = 99
ignore = ["E741"]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[dependency-groups]
dev = [
    "basedpyright>=1.29.1",
    "hypothesis>=6.133.2",
    "pytest>=8.3.5",
    "pytest-qt>=4.4.0",
    "ruff>=0.11.10",
    "ty>=0.0.1a6",
]

[tool.pytest.ini_options]
pythonpath = "."
testpaths = ["tests"]

[tool.hatch.build.targets.wheel]
packages = ["src/edon", "src/edon_ui"]
