"""Defines the core `EntityNode` class and related structures for the Edon graph.

This module provides the `EntityNode`, which is the base representation for all
nodes within the `EntityGraph`. Nodes are the primary computational units and
data containers in the graph. They manage their input and output sockets
(`EntitySocket` instances) and encapsulate specific processing logic.

The design facilitates a declarative approach for creating custom node types:
users can subclass `EntityNode` and define class-level attributes for `name`,
`node_type`, and lists of `SocketDef` objects to specify `source_socket_definitions`
and `target_socket_definitions`. The `EntityNode`'s `__post_init__` method
handles the instantiation of these sockets.

"""

from __future__ import annotations

import uuid
from dataclasses import dataclass, field
from typing import TYPE_CHECKING, Self

from edon.socket import EntitySocket, SocketRole

if TYPE_CHECKING:
    from edon.types import SocketDef


@dataclass
class EntityNode:
    """
    Represents a single node in the node editor graph. Nodes manage their input and output sockets
    and define core processing logic.

    Subclasses can be defined declaratively by setting class attributes:
    """

    # --- Instance Attributes (can be passed via __init__ generated by @dataclass) ---
    # These allow overriding class attributes or direct instantiation without subclassing.
    name: str | None = field(default=None)
    node_type: str | None = field(default=None)

    # Socket definitions default to `None` at the instance level.
    # This allows `__post_init__` to distinguish between "not provided" (use class attr)
    # and "provided as empty list []" (use the empty list).
    source_socket_definitions: list[SocketDef] | None = field(default=None)
    target_socket_definitions: list[SocketDef] | None = field(default=None)

    # --- Internal Attributes ---
    id: str = field(default_factory=lambda: str(uuid.uuid4()))
    sockets: dict[str, EntitySocket] = field(default_factory=dict, init=False)

    def __post_init__(self) -> None:
        """Finalizes node initialization after dataclass setup.

        This method resolves the node's actual name, type, and socket definitions
        by considering instance attributes, then class attributes, and finally
        applying defaults. It then creates the socket instances.
        """
        cls: type[Self] = self.__class__

        # 1. Resolve 'name'
        # Priority: Instance __init__ > Subclass.name > Derived from Subclass.__name__
        # For base EntityNode: Instance __init__ > None (remains None if not passed)
        if self.name is None: # Only if not provided via __init__
            resolved_name_attr = getattr(cls, "name", None)
            if resolved_name_attr is not None:
                self.name = resolved_name_attr
            elif cls is not EntityNode: # For subclasses without a 'name' class attribute
                derived_name = cls.__name__.replace("Node", "")
                # Keep derived_name even if "Node" wasn't present (e.g., "Minimal")
                self.name = derived_name
            # If cls is EntityNode and self.name was None (not passed to __init__), it remains None.

        # 2. Resolve 'node_type'
        # Priority: Instance __init__ > Subclass.node_type > Derived from Subclass.__name__ (lower)
        # For base EntityNode: Instance __init__ > None (remains None if not passed)
        if self.node_type is None: # Only if not provided via __init__
            resolved_node_type_attr = getattr(cls, "node_type", None)
            if resolved_node_type_attr is not None:
                self.node_type = resolved_node_type_attr
            elif cls is not EntityNode: # For subclasses without a 'node_type' class attribute
                derived_node_type = cls.__name__.lower().replace("node", "")
                self.node_type = derived_node_type
            # If cls is EntityNode and self.node_type was None, it remains None.

        # 3. Resolve 'source_socket_definitions'
        # Priority: Instance __init__ (can be []) > Subclass.source_socket_definitions (can be []) > Default []
        resolved_source_defs: list[SocketDef]
        if self.source_socket_definitions is not None: # Instance value takes precedence
            resolved_source_defs = self.source_socket_definitions
        else: # Not set on instance, try class attribute
            class_s_defs = getattr(cls, "source_socket_definitions", None) # Get actual class attribute
            resolved_source_defs = class_s_defs if class_s_defs is not None else [] # Default to [] if class attr is None or missing
        
        # 4. Resolve 'target_socket_definitions'
        # Priority: Instance __init__ (can be []) > Subclass.target_socket_definitions (can be []) > Default []
        resolved_target_defs: list[SocketDef]
        if self.target_socket_definitions is not None: # Instance value takes precedence
            resolved_target_defs = self.target_socket_definitions
        else: # Not set on instance, try class attribute
            class_t_defs = getattr(cls, "target_socket_definitions", None) # Get actual class attribute
            resolved_target_defs = class_t_defs if class_t_defs is not None else [] # Default to [] if class attr is None or missing

        # --- Create Sockets ---
        # Iterate using the final resolved definitions determined above.
        for sock_def in resolved_target_defs: # These are now guaranteed to be lists
            self._add_socket_internal(sock_def, SocketRole.TARGET)
        for sock_def in resolved_source_defs:
            self._add_socket_internal(sock_def, SocketRole.SOURCE)

        self._source_sockets: list[EntitySocket] | None = None
        self._target_sockets: list[EntitySocket] | None = None

    def _add_socket_internal(
        self,
        socket_def: SocketDef,
        role: SocketRole,
    ) -> None:
        """
        Internal method to create and add a socket to the node.

        The `parent_node` for the socket is automatically set to this node instance.
        """
        if socket_def.name in self.sockets:
            raise ValueError(
                f"Socket with name '{socket_def.name}' already exists on node '{self.name}'."
            )

        socket_instance: EntitySocket = EntitySocket(
            name=socket_def.name,
            role=role,
            node=self,
            type_info=socket_def.socket_type,
            value=socket_def.default,
        )

        self.sockets[socket_def.name] = socket_instance

    @property
    def source_sockets(self) -> list[EntitySocket]:
        if self._source_sockets is None:
            self._source_sockets = [
                sock for sock in self.sockets.values() if sock.role == SocketRole.SOURCE
            ]
        return self._source_sockets

    @property
    def target_sockets(self) -> list[EntitySocket]:
        if self._target_sockets is None:
            self._target_sockets = [
                sock for sock in self.sockets.values() if sock.role == SocketRole.TARGET
            ]
        return self._target_sockets

    def process(self) -> None:
        """
        The core computational logic of the node. Returns None.

        This method MUST be overridden by subclasses to define the node's behavior.
        It is called by the `ExecutionEngine` when the node is ready to be processed.

        Subclasses should typically:
        1. Access input sockets via `self.source_sockets['socket_name']`.
        2. Get input values:
           - Check `socket.is_connected()`.
           - If connected, access the value from the connected output socket,
             typically via `socket.connections[0].value`. The `ExecutionEngine`
             ensures upstream nodes are processed first.
           - If not connected, use the input socket's own `socket.value` as a
             default or based on node logic.
           - Ensure operations respect the `data_type` of the socket.
        3. Compute results based on these input values and the node's purpose.
        4. Set output values directly on output sockets:
           `self.target_sockets['socket_name'].value = result_value`.
           - Ensure the `result_value` is compatible with the output socket's `data_type`.

        The method signature is `-> None` because data is read from and written
        to the node's own `EntitySocket` instances. These sockets handle data type
        management and connection compatibility. The `process` method orchestrates
        the node's internal data transformation and state changes.
        """
        raise NotImplementedError(
            f"Node class '{self.__class__.__name__}' must implement the process() method."
        )

    def __repr__(self) -> str:
        return (
            f"Node(name='{self.name}', type='{self.node_type}', id='{self.id}', "
            f"sources={[sock.name for sock in self.source_sockets]}, "
            f"targets={[sock.name for sock in self.target_sockets]})"
        )
