import uuid
from dataclasses import dataclass, field
from typing import Any, Type

# Assuming socket.py is in the same directory or accessible in PYTHONPATH
from edon.socket import EntitySocket, SocketDirection


@dataclass
class SocketDef:
    name: str
    type: Type[Any]
    default: Any = None
    visual_type_key: str = "default"
    accepts_connection: bool = True


@dataclass
class EntityNode:
    """
    Represents a single node in the node editor graph. Nodes manage their input and output sockets
    and define core processing logic.

    Subclasses can be defined declaratively by setting class attributes:

    - `name: str` (optional): Defaults to the subclass name (e.g., "MyNode" -> "My").
    - `node_type: str` (optional): Defaults to the subclass name lowercased (e.g., "MyNode" -> "my").
    - `input_socket_definitions: list[tuple[str, Type[Any]]]` (optional): Defines input sockets.
    - `output_socket_definitions: list[tuple[str, Type[Any]]]` (optional): Defines output sockets.

    Example:
        ```python
        class MySimpleNode(EntityNode):
            node_type = "custom.simple"
            output_socket_definitions = [("result", int)]

            def process(self):
                self.output_sockets["result"].value = 42
        ```

    Attributes:
        name (str): Resolved display name of the node.
        node_type (str): Resolved string identifier for the type of this node.
        input_socket_definitions (list | None): Instance definitions passed at creation.
                                                Defaults to `None` to enable class attribute fallback.
        output_socket_definitions (list | None): Instance definitions passed at creation.
                                                 Defaults to `None` to enable class attribute fallback.
        id (str): Unique identifier for the node instance.
        input_sockets (dict[str, Socket]): Dictionary of created input Socket objects.
        output_sockets (dict[str, Socket]): Dictionary of created output Socket objects.
    """

    # --- Instance Attributes (can be passed via __init__ generated by @dataclass) ---
    # These allow overriding class attributes or direct instantiation without subclassing.
    name: str | None = field(default=None)
    node_type: str | None = field(default=None)

    # Socket definitions default to `None` at the instance level.
    # This allows `__post_init__` to distinguish between "not provided" (use class attr)
    # and "provided as empty list []" (use the empty list).
    input_socket_definitions: list[tuple[str, Type[Any]]] | None = field(default=None)
    output_socket_definitions: list[tuple[str, Type[Any]]] | None = field(default=None)

    # --- Internal Attributes ---
    id: str = field(default_factory=lambda: str(uuid.uuid4()))
    input_sockets: dict[str, EntitySocket] = field(default_factory=dict, init=False)
    output_sockets: dict[str, EntitySocket] = field(default_factory=dict, init=False)

    def __post_init__(self):
        """Initializes defaults and sockets based on instance or class attributes."""

        # --- Determine Final Configuration ---
        # Priority: Instance Value -> Class Attribute -> Default

        self.name = self.__class__.name or self.__class__.__name__.replace("Node", "")
        self.node_type = self.__class__.node_type or self.__class__.__name__.lower().replace("node", "")

        # Resolve input_socket_definitions: Use instance `self.input_socket_definitions` if provided (i.e., not None),
        # otherwise, try the class attribute `self.__class__.input_socket_definitions`, else default to an empty list.
        # This allows subclasses to define sockets purely via class attributes.
        input_defs = self.input_socket_definitions or self.__class__.input_socket_definitions or []
        output_defs = self.output_socket_definitions or self.__class__.output_socket_definitions or []

        # --- Create Sockets ---
        # Iterate using the final resolved definitions determined above.
        for sock_def in input_defs:
            # TODO: Consider extending definition tuple: (name, type, default_value) for sockets?
            self._add_socket_internal(sock_def.name, SocketDirection.INPUT, sock_def.type, sock_def.default)
        for sock_def in output_defs:
            self._add_socket_internal(sock_def.name, SocketDirection.OUTPUT, sock_def.type, sock_def.default)

    def _add_socket_internal(
        self, name: str, direction: SocketDirection, data_type: Type[Any], value: Any = None
    ) -> EntitySocket:
        """
        Internal method to create and add a socket to the node.
        The `parent_node` for the socket is automatically set to this node instance.
        """
        if name in self.input_sockets or name in self.output_sockets:
            raise ValueError(f"Socket with name '{name}' already exists on node '{self.name}'.")

        socket_instance = EntitySocket(
            name=name, direction=direction, parent_node=self, data_type=data_type, value=value
        )
        if direction == SocketDirection.INPUT:
            self.input_sockets[name] = socket_instance
        else:
            self.output_sockets[name] = socket_instance
        return socket_instance

    def process(self):
        """
        The core computational logic of the node.
        This method MUST be overridden by subclasses to define the node's behavior.

        Subclasses should typically:
        1. Access input sockets via `self.input_sockets['socket_name']`.
        2. Get input values: Check `socket.is_connected()` and access
           `socket.connections[0].value` (value from connected output) or use
           the socket's own `socket.value` as a default if not connected.
           The graph execution logic should ensure upstream nodes are processed first.
        3. Compute results.
        4. Set output values directly on output sockets: `self.output_sockets['socket_name'].value = result_value`.
        """
        raise NotImplementedError(f"Node class '{self.__class__.__name__}' must implement the process() method.")

    def __repr__(self) -> str:
        return (
            f"Node(name='{self.name}', type='{self.node_type}', id='{self.id}', "
            f"inputs={list(self.input_sockets.keys())}, outputs={list(self.output_sockets.keys())})"
        )
